/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CredentialsInputType: { // input type
    email: string; // String!
    password: string; // String!
    role: string; // String!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Job: { // root type
    apply: string; // String!
    company: string; // String!
    contract: string; // String!
    id: number; // Int!
    jobDescription: string; // String!
    jobRequirementContent: string; // String!
    jobRequirementList: string[]; // [String!]!
    jobRoleContent: string; // String!
    jobRoleList: string[]; // [String!]!
    location: string; // String!
    logoUrl: string; // String!
    position: string; // String!
    postedAt: string; // String!
    website: string; // String!
  }
  Mutation: {};
  Query: {};
  User: { // root type
    createdAt: string; // String!
    email: string; // String!
    id: number; // Int!
    role: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Job: { // field return type
    apply: string; // String!
    company: string; // String!
    contract: string; // String!
    id: number; // Int!
    jobDescription: string; // String!
    jobRequirementContent: string; // String!
    jobRequirementList: string[]; // [String!]!
    jobRoleContent: string; // String!
    jobRoleList: string[]; // [String!]!
    location: string; // String!
    logoUrl: string; // String!
    position: string; // String!
    postedAt: string; // String!
    website: string; // String!
  }
  Mutation: { // field return type
    addNewUser: NexusGenRootTypes['User']; // User!
    getUser: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    job: NexusGenRootTypes['Job'] | null; // Job
    jobs: Array<NexusGenRootTypes['Job'] | null>; // [Job]!
  }
  User: { // field return type
    createdAt: string; // String!
    email: string; // String!
    id: number; // Int!
    role: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Job: { // field return type name
    apply: 'String'
    company: 'String'
    contract: 'String'
    id: 'Int'
    jobDescription: 'String'
    jobRequirementContent: 'String'
    jobRequirementList: 'String'
    jobRoleContent: 'String'
    jobRoleList: 'String'
    location: 'String'
    logoUrl: 'String'
    position: 'String'
    postedAt: 'String'
    website: 'String'
  }
  Mutation: { // field return type name
    addNewUser: 'User'
    getUser: 'User'
  }
  Query: { // field return type name
    job: 'Job'
    jobs: 'Job'
  }
  User: { // field return type name
    createdAt: 'String'
    email: 'String'
    id: 'Int'
    role: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addNewUser: { // args
      input: NexusGenInputs['CredentialsInputType']; // CredentialsInputType!
    }
    getUser: { // args
      input: NexusGenInputs['CredentialsInputType']; // CredentialsInputType!
    }
  }
  Query: {
    job: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}